#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Shikanime"
email = "shikanime@shikanime.studio"

[git]
push-bookmarks = ["shikanime/*"]
sign-on-push = false

[signing]
behavior = "own"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDsUrtJU0kAg39S6Is4hOhiCIbZusi7/MHAvLYY0M7L3"
