---
dotfiles_templates_extra:
  - src: zshrc.j2
    dest: ~/.zshrc
  - src: zprofile.j2
    dest: ~/.zprofile
  - src: bash_profile.j2
    dest: ~/.bash_profile
  - src: jj_config.toml.j2
    dest: ~/.config/jj/config.toml
  - src: nix_conf.j2
    dest: ~/.config/nix/nix.conf
